version: '3.2'
services:
  web:
    image: owner_name/project_name
    command:
      - default
    ports:
      - 3000:3000
    depends_on:
      - postgres
    volumes:
      - .:/project_name
      - gems:/usr/local/bundle

  postgres:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

volumes:
  gems:
  postgres_data:
